### ISSUE TITLE
venues > monuments, public art sculpture, etc.

### ISSUE THREAD

**Issue by todrobbins** [whosonfirst/whosonfirst-placetypes#1]
Monuments, public art sculpture, etc., don't seem to fall within `venues` as defined:

```
Things with walls, basically. Things with walls that might be public (a bar) or private (your apartment) by default.
```

Maybe there could be one more level of `common optional` to include such geolocated things. Thoughts?

**Comment by thisisaaronland** [comment]
See also: https://github.com/whosonfirst/whosonfirst-placetypes/commit/b1dcc972508f047f2ed6425bcd2c2bac7b06652b
