### ISSUE TITLE
Tomba kanssa 

### ISSUE THREAD

**Issue by 622333371** [whosonfirst/whosonfirst-placetypes#30]
https://github.com/whosonfirst-data/whosonfirst-data-admin-gn/blob/master/data/126/021/452/3/1260214523.geojson

**Comment by stepps00** [comment]
Hi @622333371 is there a data issue to report with [1260214523.geojson](https://github.com/whosonfirst-data/whosonfirst-data-admin-gn/blob/master/data/126/021/452/3/1260214523.geojson)?
